// eslint-disable-next-line import/no-anonymous-default-export
export default {
  translation: {
    blackpipe: "بلاك بایب",
    dashboard: "الصفحة الرئيسية",
    rolls: "رولات",
    slitter: "شراحة",
    pieces: "مخزن شراحة",
    piece: "شريحة",
    wastes: "تلف شراحة",
    tarqeq: "الترقیق",
    tambur: "تمبور",
    s_list: "قائمة الإنتاج",
    productions: "الانتاج",
    factor_store: "مخزن مصنع",
    blackpipe_store: "مخزن بلاك بايب",
    qandelblblas_store: "مخزن قنديل بلباس",
    users: "المستخدمون",
    login: "تسجيل الدخول",
    logout: "تسجيل خروج",
    roll: "رول",
    added: "تم الاضافة",
    cancel: "الغاء",
    kg: "کغم",
    m: "متر",
    mm: "ملم",
    delete: "حذف",
    deleted: "تم الحذف",
    edit: "تعدیل",
    code: "کود",
    roll_code: "کود رول",
    thikness: "سمك",
    tarqeq_length: "الطول بعد الترقيق",
    tarqeq_thikness: "السمك بعد الترقيق",
    width: "عرض",
    weight: "وزن",
    net_weight: "الوزن الصافي",
    gross_weight: "الوزن الإجمالي",
    type: "نوع",
    hr: "HR",
    gi: "GI",
    cr: "CR",
    madein: "صنع في",
    rollQuality: "جودة الرول",
    comment: "تعليق",
    deleted_comment: "السبب الحذف",
    deleted_date: "تاريخ الحذف",
    deleted_by: "تم الحذف من قبل",
    added_by: "تم الاضافة من قبل",
    upload_image: "تحميل الصورة",
    tLength: "الطول النظري",
    aLength: "الطول الفعلي",
    date: "التاريخ",
    time: "الوقت",
    update: "التحديث",
    updated: "تم التحدث",
    slit: "قطع",
    slited: "تم القطع",
    remains: "بقايا/تلف",
    devid_into: "تقسم إلى",
    devided_into: "مقسمة إلى",
    real_width: "العرض الواقعي",
    slitted_by: "تم القطع من قبل",
    search: "بحث",
    day_series: "تسلسل اليوم",
    piece_series: "تسلسل شريحة",
    actual_weight: "الوزن الواقعي",
    total_weight: "الوزن الكلي",
    total_real_weight: "إجمالي الوزن الواقعي",
    total: "مجموع",
    s_packet_qnt: "الكمية القياسية في الربطة",
    s_packet_w: "الوزن القياسية للربطة",
    s_piece_w: "الوزن القياسية للربطة",
    line: "خط",
    quality: "الجودة",
    produce: "أنتج",
    packet_qnt: "عدد الربطة",
    packet_w: "الوزن الربطة",
    list_name: "اسم القائمة",
    pipes: "عدد",
    send: "ارسال",
    sent: "تم ارسال",
    qnt: "عدد",
    send_to: "ارسال إلى",
    sent_to: "تم ارسال إلى",
    from: "من",
    car_no: "رقم السياره",
    car_type: "نوع السيارة",
    sell: "بيع",
    sell_to: "يباع الي",
    sell_by: "يباع من قبل",
    current_rolls: "الرولات الموجودةالحاليا",
    deleted_rolls: "الرولات المحذوفة",
    add_roll: "إضافة رول",
    current_slitteds: "الرولات المقطوعة",
    deleted_slitteds: "الشرائح محذوفة",
    current_pieces: "الشرائح الموجودة حاليا",
    deleted_pieces: "الشرائح المحذوفة",
    add_piece: "إضافة شريحة",
    current_remainings: "البقايا/تلف",
    add_remaining: "إضافة البقايا/تلف",
    current_tambured: "مرسل الی تمبور",
    deleted_tambured: "المحذوفات",
    tambured_by: "مرسل من جهة",
    tambured: "ارسل",
    add_list: "إضافة القائمة",
    current_lists: "القوائم الحالية",
    sent_products: "المنتجات المرسلة",
    sent_qandel: "المنتجات المرسلة من المغزن",
    add_products: "إضافة منتج",
    current_tarqeq: "القطع المرقق",
    role: "دور",
    username: "اسم المستخدم",
    name: "اسم",
    phone: "هاتف",
    password: "كلمة المرور",
    add_user: "إضافة مستخدم",
    empty_store: "هذا المغزن فارغ",
    select_line: "اختر الخط",
    select_line_hasto: "يجب عليك أن تختار الخط الأول",
    select_list: "يجب عليك تحديد قائمة أولاً",
    on_product: "هل أنت متأكد من أنك تريد إنتاج؟",
    on_slit: "هل أنت متأكد من أنك تريد القطع؟",
    on_send: "هل أنت متأكد من أنك تريد إرسال؟",
    on_tambur: "هل أنت متأكد من أنك تريد تمبور؟",
    on_tarqeq: "هل أنت متأكد من أنك تريد الترقق؟",
    on_update: "هل أنت متأكد أنك تريد التحديث؟",
    on_delete: "هل أنت متأكد أنك تريد حذف؟",
    on_delete_per: "هل أنت متأكد أنك تريد الحذف نهائيًا؟",
    on_add: "هل أنت متأكد أنك تريد إضافة؟",
    not_enough: "لا يكفي الإنتاج في المتجر!",
    reports: "التقارير",
    technician: "فني",
    Report_of: "تقرير عن",
    from_time: "من",
    to_time: "الي",
    speed: "سرعة",
    report_form: "رأس نموذج التقرير",
    report_list: "أنواع التقارير",
    year: "سنة",
    none: "غير ذالك",
    all: "كل",
    slitted_rolls: "الرولات المقطوعة",
    empty_store_line: "لا توجد بيانات بالجودة ({{showedQuality}})",
    print: "طبع",
    driverName: "اسم السائق",
    driverPhone: "هاتف السائق",
    sold_productions: "المنتجات المباعة",
    sold_qandelblbas: "من مغزن قندل بلباس",
    sold_blackpipe: "من مغزن بلاك بايب",
    sold_factory: "من مغزن مصنع",
    all_sold: "جميع البيانات المباعة",
    size: "حجم",
    seller: "البائع",
    sold_remainings: "من البقايا",
    Data_Not_Found: "لم يتم العثور على بيانات",
    page_not_found: "لم يتم العثور على الصفحة",
    allproducts: "جميع المنتجات",
    for_order: "للطلب والاستفسارات",
    add_spare_list: "إضافة قائمة المواد الاحطياطية",
    spare_lists: "قائمة المواد الاحطياطية",
    spare_parts: "المواد الاحطياطية",
    add_spare: "إضافة المواد الاحطياطية",
    used_spares: "المواد الاحطياطية مستعملة",
    use: "استخدام",
    used: "مستعمل",
    usedBy: "استعمل من قبل",
    gaveTo: "أعطى ل",
    activity: "نشاط",
    on_use: "هل أنت متأكد أنك تريد استخدام؟",
    reset_password: "إعادة تعيين كلمة المرور",
    newPassword: "كلمة مرور جديدة",
    reset: "اعاده تعيين",
    reseted: "تمت إعادة التعيين",
    on_reset: "هل أنت متأكد من أنك تريد إعادة تعيين كلمة المرور؟",
  },
};
