// eslint-disable-next-line import/no-anonymous-default-export
export default {
  translation: {
    blackpipe: "Black Pipe",
    dashboard: "Dashboard",
    rolls: "Rolls",
    slitter: "Slitter",
    pieces: "Pieces",
    piece: "Pieces",
    wastes: "Wastes",
    tarqeq: "Thinning",
    tambur: "Tambur",
    s_list: "Production List",
    productions: "Productions",
    factor_store: "Factor Store",
    blackpipe_store: "Black Pipe Store",
    qandelblblas_store: "Qandel Blbas Store",
    users: "Users",
    login: "Login",
    logout: "Log out",
    roll: "Rolls",
    added: "Added",
    cancel: "Cancel",
    kg: "kg",
    m: "m",
    mm: "mm",
    delete: "Delete",
    deleted: "Deleted",
    edit: "Edit",
    code: "Code",
    roll_code: "Roll Code",
    thikness: "Thickness",
    tarqeq_length: "Thinning Length",
    tarqeq_thikness: "Thinning Thikness",
    width: "Width",
    weight: "Weight",
    net_weight: "Net Weight",
    gross_weight: "Gross Weight",
    type: "Type",
    hr: "HR",
    gi: "GI",
    cr: "CR",
    madein: "Made In",
    rollQuality: "Roll Quality",
    comment: "Comment",
    deleted_comment: "Deleted Reason",
    deleted_date: "Deleted Date",
    deleted_by: "Deleted By",
    added_by: "Added By",
    upload_image: "Upload Image",
    tLength: "Theory Length",
    aLength: "Actual Length",
    date: "Date",
    time: "Time",
    update: "Update",
    updated: "Updated",
    slit: "Slit",
    slited: "Slitted",
    remains: "Remains",
    devid_into: "Divide Into",
    devided_into: "Divided Into",
    real_width: "Real Width",
    slitted_by: "Slitted By",
    search: "Search",
    day_series: "Day Series",
    piece_series: "Piece Series",
    actual_weight: "Actual Weight",
    total_weight: "Total Weight",
    total_real_weight: "Total Real Weight",
    total: "Total",
    s_packet_qnt: "Standard Packet Quantity",
    s_packet_w: "Standard Packet Weight",
    s_piece_w: "Standard Piece Weight",
    line: "Line",
    quality: "Quality",
    produce: "Produce",
    packet_qnt: "Packet Quantity",
    packet_w: "Packet Weight",
    list_name: "List Name",
    pipes: "Pieces",
    send: "Send",
    sent: "Sent",
    qnt: "Quantity",
    send_to: "Send To",
    sent_to: "Sent To",
    from: "From",
    car_no: "Car Number",
    car_type: "Car Type",
    sell: "Sell",
    sell_to: "sell to",
    sell_by: "sold By",
    current_rolls: "Current Rolls",
    deleted_rolls: "Deleted Rolls",
    add_roll: "Add Roll",
    current_slitteds: "Slitted Rolls",
    deleted_slitteds: "Deleted Slitted Rolls",
    current_pieces: "Current Pieces",
    deleted_pieces: "Deleted Pieces",
    add_piece: "Add Piece",
    current_remainings: "Current Remainings",
    add_remaining: "Add Remaining Piece",
    current_tambured: "Sent to Tambur",
    deleted_tambured: "Removed from Tambur",
    tambured_by: "Tambured By",
    tambured: "Tambured",
    add_list: "Add List",
    current_lists: "Current Lists",
    sent_products: "Sent Products",
    sent_qandel: "Sent Products",
    add_products: "Add Product",
    current_tarqeq: "Tarqeqed Pieces",
    role: "Role",
    username: "Username",
    name: "Name",
    phone: "Phone",
    password: "Password",
    add_user: "Add User",
    empty_store: "This Store is Empty",
    select_line: "Select Line",
    select_line_hasto: "You have to select a Line First",
    select_list: "You have to select A list First",
    on_product: "Are you sure you want to Produce?",
    on_slit: "Are you sure you want to Slit?",
    on_send: "Are you sure you want to Send?",
    on_tambur: "Are you sure you want to Tambur?",
    on_tarqeq: "Are you sure you want to Tarqeq?",
    on_update: "Are you sure you want to update?",
    on_delete: "Are you sure you want to DELETE?",
    on_delete_per: "Are you sure you want to DELETE PERMANENTLY?",
    on_add: "Are you sure you want to Add?",
    not_enough: "Not Enought Production in Store!",
    reports: "Reports",
    technician: "Technician",
    Report_of: "Report Of",
    from_time: "From Time",
    to_time: "End Time",
    speed: "Speed",
    report_form: "Report Form Header",
    report_list: "Report Types",
    year: "Year",
    none: "None",
    all: "All",
    slitted_rolls: "Slitted Rolls",
    empty_store_line: "There is No data With Quality ({{showedQuality}})",
    print: "Print",
    driverName: "Driver Name",
    driverPhone: "Driver Phone",
    sold_productions: "Sold Productions",
    sold_qandelblbas: "From QandelBlbas Store",
    sold_blackpipe: "From blackPipe Store",
    sold_factory: "From Factory Store",
    all_sold: "All Sold Data",
    size: "Size",
    seller: "Seller",
    sold_remainings: "From Wastings",
    Data_Not_Found: "Data Not Found",
    page_not_found: "Page Not Found",
    allproducts: "All Products",
    for_order: "For Order and Inquiries",
    add_spare_list: "Add Spare List",
    spare_lists: "Spare Lists",
    spare_parts: "Spare Parts",
    add_spare: "Add Spare",
    used_spares: "Used Spares",
    use: "Use",
    used: "Used",
    usedBy: "Used By",
    gaveTo: "Gave To",
    activity: "Activity",
    on_use: "Are you sure you want to USE?",
    reset_password: "Reset Password",
    newPassword: "New Password",
    reset: "Reset",
    reseted: "Reseted",
    on_reset: "Are you sure you want to RESET PASSWORD?",
  },
};
