// eslint-disable-next-line import/no-anonymous-default-export
export default {
  translation: {
    blackpipe: "بلاك پایپ",
    dashboard: "سەرەکی ",
    rolls: "ڕۆلەکان",
    slitter: "شراحە",
    pieces: "کۆگای شراحە",
    piece: "پارچە",
    wastes: "پاشماوە",
    tarqeq: "تەنککردەوە",
    tambur: "تەمبور",
    s_list: "لیستی بەرهەمەکان",
    productions: "بەرهەمەکان",
    factor_store: "کۆگای کارگە",
    blackpipe_store: "کۆگای بلاك پایپ",
    qandelblblas_store: "کۆگای قندیل بلباس",
    users: "بەکارهێنەرەکان",
    login: "چوونەژوورەوە",
    logout: "دەرچوون",
    roll: "ڕۆل",
    added: "زیاد کرا",
    cancel: "گەڕانەوە",
    kg: "کگم",
    mm: "ملم",
    m: "م",
    delete: "سڕینەوە",
    deleted: "سڕایەوە",
    edit: "دەستکاری",
    code: "کۆد",
    roll_code: "کۆدی ڕۆڵ",
    thikness: "ئەستووری",
    tarqeq_length: "درێژی دوای تەرقیق",
    tarqeq_thikness: "ئەستووری دوای تەرقیق",
    width: "پانی",
    weight: "کێش",
    net_weight: "کێشی تەواو",
    gross_weight: "کێشی گشتی",
    type: "جۆر",
    hr: "HR",
    gi: "GI",
    cr: "CR",
    madein: "دروستکراوی",
    rollQuality: "کوالیتی ڕۆڵ",
    comment: "تێبینی",
    deleted_date: "ڕێککەوتی سڕینەوەی",
    deleted_comment: "هۆکاری سڕانەوە",
    deleted_by: "سڕاوەتەوە لە لایەن",
    added_by: "زیادکراوە لە لایەن",
    upload_image: "زیادکردنی وێنە",
    tLength: "درێژی تیۆری",
    aLength: "درێژی تەواو",
    date: "ڕێککەوت",
    time: "کاژێر",
    update: "چاککردن",
    updated: "چاککرا",
    slit: "بڕین",
    slited: "بڕدرا",
    remains: "ماوە",
    devided_into: "دابەشبووە بۆ",
    devid_into: "دابەشبێ بۆ",
    real_width: "پانی تەواو",
    slitted_by: "بڕاوە لە لایەن",
    search: "گەڕان",
    day_series: "ڕیزبەندی ڕۆل لە ڕۆژ",
    piece_series: "ڕیزبەندی شریحە",
    actual_weight: "کێشی ڕاست",
    total_weight: "کێشی گشتی",
    total_real_weight: "کێشی تەواوی گشتی",
    total: "کۆی گشتی",
    s_packet_qnt: "بڕی پێوانەیی لە پاکەت",
    s_packet_w: "کێشی پێوانەیی پاکەت",
    s_piece_w: "کێشی پێوانەیی ١ دانە",
    line: "‌هێڵ",
    quality: "کوالێتی",
    produce: "بەرهەمهێنان",
    packet_qnt: "بڕی پاکەت",
    packet_w: "کێشی پاکەت",
    list_name: "بەرهەم",
    pipes: "بۆری",
    send: "ناردن",
    sent: "نێردرا",
    qnt: "بڕ",
    send_to: "ناردن بۆ",
    sent_to: "نێردراو بۆ",
    from: "لە لایەن",
    car_no: "ژمارەی ئۆتۆمبێل",
    car_type: "جۆری ئۆتۆمبێل",
    sell: "فرۆشتن",
    sell_to: "فرۆشتن بە",
    sell_by: "فرۆشراوە لەلایەن",
    current_rolls: "ڕۆلی بەردەست",
    deleted_rolls: "ڕۆلی سڕاوە",
    add_roll: "زیادکردنی ڕۆل",
    current_slitteds: "ڕۆلی بڕدراو",
    deleted_slitteds: "ڕۆلی بڕدراوی سڕاوە",
    current_pieces: "شریحەی بەردەست",
    deleted_pieces: "شریحەی سڕاوە",
    add_piece: "زیادکردنی شریحە ",
    current_remainings: "پاشماوەی بەردەست",
    add_remaining: "زیادکردنی پاشماوەی شریحە",
    current_tambured: "نێردراو بۆ تەمبور",
    deleted_tambured: "سڕاوە لە تەمبور",
    tambured_by: "تەمبور کراوە لە لایەن",
    tambured: "تەمبور کرا",
    add_list: "تۆمارکردنی بەرهەم",
    current_lists: "تۆماری بەرهەم",
    sent_products: "بەرهەمی ڕۆشتوو لە کارگە",
    sent_qandel: "بەرهەمی ڕۆیشتوو لە کۆگا",
    add_products: "زیادکردنی بەرهەم",
    current_tarqeq: "شریحەەی تەرقیقکراوی بەردەست",
    role: "ئەرک",
    username: "ناوی بەکارهێنەر",
    name: "ناو",
    phone: "ژ. مۆبایل",
    password: "وشەی تێپەڕ",
    add_user: "زیادکردنی بەکارهێنەر",
    empty_store: "هیچ بەرهەمێک لەم کۆگایە بەردەست نییە",
    select_line: "‌هێلێک هەڵبژێرە",
    select_line_hasto: "پێویستە هێڵێك هەڵبژێری",
    select_list: "پێویستە لیستێک هەڵبژێری",
    on_product: "ئایا دڵنیای لە زیادکردنی بۆ تۆماری بەرهەمێنان",
    on_send: "ئایا دڵنیای لە گواستنەوەی؟",
    on_tambur: "ئایا دڵنیای لە ناردنی بۆ تەمبور؟",
    on_tarqeq: "ئایا دڵنیای لە تەرقیق کردن؟",
    on_slit: "ئایا دڵنیای لە بڕینی",
    on_update: "ئایا دڵنیای لە چاککردنی؟",
    on_delete: "ئایا دڵنیای لە سڕینەوەی؟",
    on_delete_per: "ئایا دڵنیای لە سڕینەوەی بە تەواوەتی؟",
    on_add: "ئایا دڵنیای لە زیادکردن؟",
    not_enough: "بڕی داواکراو بەردەست نییە",
    reports: "ڕاپۆرتەکان",
    Report_of: "ڕاپۆرتی",
    technician: "تەکنیک کار",
    from_time: "کاتی دەستپێک",
    to_time: "کۆتایی هاتن",
    speed: "خێرایی",
    report_form: "فۆرمی ڕاپۆرت",
    report_list: "جۆری ڕاپۆرت",
    year: "ساڵ",
    none: "هیچ کام لەمانە",
    all: "هەموو لەمانە",
    slitted_rolls: "ڕۆڵە بڕاوەکان",
    empty_store_line: "هیچ داتایەکی کوالیتی ({{showedQuality}}) بەردەست نییە",
    print: "چاپکردن",
    driverName: "ناوی شوفێر",
    driverPhone: "ژ. مۆبایلی شوفێر",
    sold_productions: "بەرهەمی فرۆشراو",
    sold_qandelblbas: "لە قندل بلباس",
    sold_blackpipe: "لە بلاك پایپ",
    sold_factory: "لە کارگە",
    all_sold: "هەموو فرۆشراوەکان",
    size: "قەبارە",
    seller: "فرۆشیار",
    sold_remainings: "لە پارچەی ماوە",
    Data_Not_Found: "هیچ داتایەک نەدۆزرایەوە",
    page_not_found: "لاپەرە نەدۆزرایەوە",
    allproducts: "هەموو بەرهەمەکان",
    for_order: "بۆ داواکردن",
    add_spare_list: "زیاد کردنی لیستی پارچە یەدەک",
    spare_lists: "لیستی یەدەک",
    spare_parts: "پارچە یەدەکەکان",
    add_spare: "زیاد کردنی یەدەگ",
    used_spares: "پارچەی یەدەگی بەکارهاتوو",
    use: "بەکارهێنان",
    used: "بەکارهات",
    usedBy: "بەکارهاتووە لەلایەن",
    gaveTo: "دراوە بە",
    activity: "چالاکی",
    on_use: "ئایا دڵنیای لە بەکارهێنانی؟",
    reset_password: "نوێکردنەوەی وشەی تێپەر",
    newPassword: "وشەی تێپەری نوێ",
    reset: "نوێکردنەوە",
    reseted: "نوێکرایەوە",
    on_reset: "ئایا دڵنییای لە نوێکردنەوەی وشەی تێپەر",
  },
};
